config/routes.rb
Grass::Application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resources :names
  get :state_data, :to => "names#state_data"
  resources :home, only: [:new]
  resources :sessions, only: [:destroy, :new, :create]
  get :about, :to => "home#about"
  root 'home#new'
  

  

end

app/models/identity.rb
class Identity < ActiveRecord::Base
	belongs_to :names
	belongs_to :users
	belongs_to :states
end

app/models/name.rb
# == Schema Information
#
# Table name: names
#
#  id                   :integer          not null, primary key
#  first_name           :string(255)
#  historical_percent   :string(255)
#  historical_ratio     :string(255)
#  historical_rank      :string(255)
#  alive_today          :text
#  most_common_age      :text
#  births_yearly        :text
#  birth_ratios         :string(255)
#  birth_precentages    :string(255)
#  etymology            :text
#  alternative_versions :text
#  notable_people       :text
#

class Name < ActiveRecord::Base
	has_many :identities
	has_many :users, through: :identities
	# validates_presence_of :name

	def format_name(word, hash)
		 
    self.first_name = word
		self.interpretation = hash[:pods]["Input interpretation"].pop if hash[:pods]["Input interpretation"]
    self.etymology = hash[:pods]["Etymology"].pop if hash[:pods]["Etymology"]
    self.alternative_versions = hash[:pods]["Alternate versions"].pop if hash[:pods]["Alternate versions"]
    self.notable_people = hash[:pods]["Notable people named #{self.first_name}"].pop if hash[:pods]["Notable people named #{self.first_name}"]

    if hash[:pods]["Estimates for current US population"]

    	api_value = hash[:pods]["Estimates for current US population"].pop

			historical_percents(api_value)
			historical_ratios(api_value)
			historical_ranks(api_value)
			most_common_ages(api_value)
    end

    if hash[:pods]["Information for US births"]
    	api_value = hash[:pods]["Information for US births"].pop

    	births_per_year(api_value)
    	birth_ratio(api_value)
    	birth_precentage(api_value)
    end
	end

#### "Estimates for current US population" #####


	def historical_percents(api_value)
		self.historical_percent = api_value.scan(/.\d+%/).pop  #18%
	end

	def historical_ratios(api_value)
		self.historical_ratio = api_value.scan(/\d+ in \d+/).pop 
	end

	def historical_ranks(api_value)
		self.historical_rank = api_value.scan(/\d+th/).pop 
	end

	def most_common_ages(api_value)
		self.most_common_age = api_value.scan(/\d+ (?=years)/).pop
	end

#### "Information for US births" #####

  def births_per_year(api_values)
  	self.births_yearly = api_values.scan(/\d+ (?=people per)/).pop
  end

  def birth_ratio(api_value)
  	self.birth_ratios = api_value.scan(/\d+ in \d+/).pop
  end

  def birth_precentage(api_value)
		self.birth_precentages = api_value.scan(/.\d+%/).pop
  end

end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :identities
	has_many :users, through: :identities
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  email           :string(255)      not null
#  password_digest :string(255)
#  name_id         :integer
#

class User < ActiveRecord::Base
	# include ActiveModel::Validations

	has_many :identities
	has_many :names, through: :identities
	has_many :states, through: :identities
  accepts_nested_attributes_for :states, :names

  validates_presence_of :username
  validates_uniqueness_of :username
  validates_presence_of :email
  # validates_format_of :email, with: /^[\w\d]+$/ on: :create, message: "is invalid"
  validates_length_of :password, :minimum => 8, :maximum => 25
  has_secure_password
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.  

	protect_from_forgery with: :exception

  def authenticate!
    redirect_to root_path unless current_user
  end

  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

	  helper_method :current_user
    helper :formatting

  private 

    def render_404
      render :template => 'error_pages/404', :layout => false, :status => :not_found
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def new
		@name = Name.new
	end


	def about
	end


end

app/controllers/names_controller.rb
class NamesController < ApplicationController
require "call"


	def create
		given_name = params[:name][:first_name]
		given_name.capitalize!
		name = Name.where(first_name: given_name).pop
	  if name == nil 
	    name_raw = ::Call.new.call_api(given_name)
	    name = Name.new(name_params)
	    name.format_name(given_name, name_raw)
	    name.save!
	  end
    redirect_to name_path(name.id) 
	end


	def show
		@name = Name.find(params[:id])
		if @name.interpretation == nil
			flash[:notice] = "We have no data for that name, please try a different name"
			render :template => "home/new"
		end
		# Identity.create(name_id: @name.id, user_id: current_user.id) if current_user
		current_user.name = @name if current_user
	end

	def state_data
		name = params[:state][:name]
		name.capitalize!
		@state = State.where(name: name).pop
    respond_to do |format|
      format.js
    end 
	end


		private

	  def name_params
	    params.require(:name).permit(:id, :name, :interpretation, :most_common_age, :alive_today, :etymology, :named_per_year)
	  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.find_by_username(params[:username])
    @user = session[:user_id]
  end

  def create
    @user = User.find_by_username(params[:username])

    if @user && @user.authenticate(params[:password])
      login(@user)
      flash[:success] = "Welcome, #{@user.username}!"
      redirect_to root_path #action: 'show', id: @user.id
    else
      flash[:notice] = "An error occured, please try again."
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
			if @user.save!
				login(@user)
			end
			redirect_to user_path(@user.id)
	end

	def show
		@user = User.find(params[:id])
	end



	private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :name_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def nil_value(value)
		puts "application helper" * 9
		ap params
	  value.include?("nil") ? "no data".html_safe : "#{value}"
	end

end

app/helpers/formatting_helper.rb
module FormattingHelper

	def format_name(name)
		name.capitalize
	end

end

app/views/home/about.html.haml
.row
	.col-sm-8.col-md-offset-2
		%h2 Welcome to grass.io 
		%h4 Where does the data from?
		%p We take data from Wolfram Alpha, a computable knowledge engine. If you have an Iphone or an Android phone you have used this technology through speech recognition. As of 2008 the government makes data more available and we also tap into that. 
		%h4 How is the application managed?
		%p Our platform, is an Open Source MIT License. Built and maintained by: 
		=link_to "Katharine VanderDrift", "http://katharine.org" 

app/views/home/new.html.haml
.row.text-center.col-xs-12#intro
	%h3#main_page_header Watch Your Data Grow
	%p#intro Let's start with your first name...
.row

%br
.row.text-center.col-xs-12
	#errors
	= render "names/new_name_form"

.row.text-center.col-xs-12
	

/ 	%p Data Powered By:
/ 	=link_to " Wolfram Alpha  &", "http://www.wolframalpha.com/about.html" 
/ 	=link_to " US Government ", "http://www.data.gov/"
				
/ .row.col-xs-12
/ 	/ #object.pullUp
/ .row.col-xs-12

.row.col-xs-12
	#object.pullUp
	/ #object2.pullUp

app/views/layouts/_footer.html.haml
%footer.text-center.navbar  
	%ul#footer_credit
		%li Data Powered by:
		%li=link_to " Wolfram Alpha", "http://www.wolframalpha.com/about.html" 
		%li &
		%li=link_to " US Government ", "http://www.data.gov/"
	%p 2014 &copy; grass.io - Watch Your Data Grow 

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :class => "flash_#{name} text-center"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand= link_to image_tag("grass_logo.png"), root_path
  / Collect the nav links, forms, and other content for toggling
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav.pull-right
      %li=link_to "About", about_path
      - if current_user
        %li=link_to "Profile", user_path(current_user.id)
        %li=link_to 'Logout', session_path(current_user.id), :method => :delete
      - else
        %li=link_to "Create Account", new_user_path, id: "new_user"
        %li=link_to "Login", new_session_path
      
      


        

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title grass.io - Watch Your Data Grow
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
		%body
			= render "/layouts/navigation"
			= render "/layouts/messages"
			/ #user_form
			#ajax_loader
				%h3 Please wait while we gather your data...
			#wrapper.container
				= yield
			/ .container
			/ 	.row
			/ 		.span9.centred
			/ - if flash[:notice]
			/ 	.notice=flash[:notice]
			= render "layouts/footer"


    

app/views/names/_name_table.html.haml
.grid_12
	%h1.text-center Discover Your Name
	%table.flat-table
		%thead
			%tr 
				%th Interpretation
				%th Etymology
				%tr
					%td= @name.interpretation
					%td= @name.etymology
	%table.flat-table
		%thead
			%tr 
				%th Nicknames
				%tr
					%td= @name.alternative_versions ? @name.alternative_versions : "no data available"
	%h3.text-center Historical Population Data United States
	%table.flat-table
		%thead
			%tr 
				%th Ratio
				%th Rank
				%th Alive Population % 
				%th Most Common Age
				%tr.text-center
					%td= "#{@name.historical_ratio} people are named #{@name.first_name}" ? @name.historical_ratio : "no data available"
					%td= "#{@name.historical_rank} most common name" ? @name.historical_rank : "no data available"
					%td= "#{@name.historical_percent} named #{@name.first_name}" ? @name.historical_percent : "no data available"
					%td= "#{@name.most_common_age} years old" ? @name.most_common_age : "no data available"
	%h3.text-center Birth Data 2012 -United States
	%table.flat-table
		%thead
			%tr 
				%th Ratio
				%th Birth Percentage
				%th Total Named in 2012
				%tr.text-center
					%td= "#{@name.birth_ratios} born in 2012 were named #{@name.first_name}" ? @name.birth_ratios : "no data available"
					%td= @name.birth_precentages ? @name.birth_precentages : "no data available"
					%td= "#{@name.births_yearly} people were named #{@name.first_name}" ? @name.births_yearly : "no data available"


	%h3.text-center Well Known People with Your Name (Global)
	%table.flat-table
		%thead
			%tr 
				%th Notable People
				%tr.text-center
					%td= @name.notable_people ? @name.notable_people : "no data available"
						

app/views/names/_new_name_form.html.haml
.col-xs-12.text-center
	=form_for @name do |t|
		=render "shared/error_messages", :target => @name
		=t.text_field :first_name, placeholder: "Your First Name..", :autofocus => true, id: "name_field", required: true
		=t.submit "Grow", class: " btn btn-primary", id: "get_name"

app/views/names/_state_table.html.haml
.grid_12
	%h1.text-center Discover Your State
	%table.flat-table
		%thead
			%tr.text-center
				%th Name
				%th Abbreviation
				%th Per Capital Income
				%th Percent w/ College Degree
				%tr.text-center
					%td= @state.name
					%td= @state.abbreviation
					%td= number_to_currency(@state.per_capita_income)
					%td= "#{@state.percent_college_degree} %"

app/views/names/_table_data.html.haml
.grid_12
	%h1.text-center Discover Your Name
	%table.flat-table
		%thead
			%tr 
				%th Interpretation
				%th Etymology
				%tr
					%td= @name.interpretation
					%td= @name.etymology
	%table.flat-table
		%thead
			%tr 
				%th Nicknames
				%tr
					%td= @name.alternative_versions
	%h3.text-center Historical Population Data United States
	%table.flat-table
		%thead
			%tr 
				%th Ratio
				%th Rank
				%th Alive Population % 
				%th Most Common Age
				%tr.text-center
					%td= "#{@name.historical_ratio} people are named #{@name.first_name}"
					%td= "#{@name.historical_rank} most common name"
					%td= "#{@name.historical_percent} named #{@name.first_name}"
					%td= "#{@name.most_common_age} years old"
	%h3.text-center Birth Data 2012 -United States
	%table.flat-table
		%thead
			%tr 
				%th Ratio
				%th Birth Percentage
				%th Total Named in 2012
				%tr.text-center
					%td= "#{@name.birth_ratios} born in 2012 were named #{@name.first_name}"
					%td= @name.birth_precentages
					%td= "#{@name.births_yearly} people were named #{@name.first_name}"


	%h3.text-center Well Known People with Your Name (Global)
	%table.flat-table
		%thead
			%tr 
				%th Notable People
				%tr.text-center
					%td= @name.notable_people
						

app/views/names/create.js.erb
$('<%= j render "name_table" %>')

app/views/names/show.html.haml
= render "names/name_table"
#state_table
#state_graph
#state_data_form
#test
	%h1.text-center Enter Your State
	%p.text-center Only available to United States
	= render "states/form"

app/views/names/state_data.js.erb
$("#state_data_form").hide() 
$('#state_table').append("<%= j render(partial: 'names/state_table', object: @state) %>");
// $("#test").text("<%= j @state.name %>")
var capitalIncome = '<%= @state.per_capita_income %>';
Highcharts.setOptions({
   colors: ['#50B432', '#00FF00']
  });

$(function () {
  $('#test').highcharts({
      chart: {
          type: 'column'
      },
      title: {
          text: 'Per Capital Personal Income for ' + '<%= j @state.name %>' + ' Compared to National Average'
      },
      subtitle: {
          text: 'Source: 2012 US Government Data'
      },
      xAxis: {
         categories: [
	         'Data From 2012'
         ]
      },
      yAxis: {
          title: {
              text: 'Per Capital Personal Income'
          }
      },
       tooltip: {
	        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
	        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
	            '<td style="padding:0"><b>${point.y:.0f} dollar</b></td></tr>',
	        footerFormat: '</table>',
	        shared: true,
	        useHTML: true
      },
      series: [{
          name: 'United Sates',
          data: [42693]

      }, {
          name: '<%= j @state.name %>',
          data: [Number(capitalIncome)]

      }]
  });
});

app/views/shared/_error_messages.html.haml
- if target.errors.any?
  %h2
    = pluralize(target.errors.count, "error")
    prohibited this record from being saved:
  %ul
    - target.errors.full_messages.each do |msg|
      %li= msg

app/views/states/_form.html.haml
.col-xs-12.text-center
	= form_for :state, method: :get, url: state_data_path, remote: true do |t|
		= t.text_field :name
		= t.submit "Grow", class: "btn btn-primary" 

app/views/users/_form.html.haml
/ %form.form-horizontal{:role => "form"}
/ #form_box

= form_for @user, :html => { :class => "form-inline{:role => 'form'}",  :id=> "new_user_form"} do |t|
	=render "shared/error_messages", :target => @user
	.form-group.col-sm-3
		= t.label :username, class: "control-label"
		= t.text_field :username, class: "form-control", placeholder: "username", required: true
		= t.label :email, class: "control-label"
		= t.text_field :email, class: "form-control", placeholder: "email", required: true
		= t.label :password, class: "control-label"
		= t.password_field :password, class: "form-control", placeholder: "password", required: true
		= t.label :confirm, class: "control-label"
		= t.password_field :password_confirmation, class: "form-control", placeholder: "confirm password", required: true
		%br
		= t.submit "create", class: " btn btn-primary"

app/views/users/create.html.haml
= render "users/new_user_form"

app/views/users/home.html.haml
.row.text-center.col-xs-12#intro
	%h3 Watch Your Data Grow
	%p Let's start with your first name...
.row

/ %br
/ .row.text-center.col-xs-12

/ 	%p Data Powered By:
/ 	=link_to " Wolfram Alpha  &", "http://www.wolframalpha.com/about.html" 
/ 	=link_to " US Government ", "http://www.data.gov/"
				
/ .row.col-xs-12
/ 	/ #object.pullUp
/ .row.col-xs-12


= render "layouts/footer"

app/views/users/new.html.haml
= render "users/form"

app/views/users/show.html.haml
%h2= "Welcome #{@user.username}"

%h2=@user.identities